#!/bin/sh

cd /usr/local/home/jfiat/MIRROR_EIFFEL_WORLD

echo ----------------- >> logs/update_ALL.log
echo Updating all git MIRROR >> logs/update_ALL.log

echo update_freeelks - `date` >> logs/update_ALL.log 2>&1
./ALL/update_freeelks >> logs/update_ALL.log 2>&1

echo update_EiffelWebNino - `date` >> logs/update_ALL.log 2>&1
./ALL/update_EiffelWebNino >> logs/update_ALL.log 2>&1

echo update_eTokyoCabinet - `date` >> logs/update_ALL.log 2>&1
./ALL/update_eTokyoCabinet >> logs/update_ALL.log 2>&1

echo update_eiffelstudio_curl - `date` >> logs/update_ALL.log 2>&1
./ALL/update_eiffelstudio_curl >> logs/update_ALL.log 2>&1

echo update_ejson - `date` >> logs/update_ALL.log 2>&1
./ALL/update_ejson >> logs/update_ALL.log 2>&1

echo update_gobo - `date` >> logs/update_ALL.log 2>&1
./ALL/update_gobo >> logs/update_ALL.log 2>&1

echo ----------------- - `date` >> logs/update_ALL.log
