#!/bin/sh

mkdir ../eel
cd ../eel
git init
git config core.bare true
git remote add --mirror -f origin git://github.com/clemahieu/eel.git
git remote add -f mirror git@github.com:Eiffel-World/eel.git
git fetch origin
git fetch mirror
git push --mirror mirror
