#!/bin/sh

mkdir ../eTokyoCabinet
cd ../eTokyoCabinet
git init
git config core.bare true
git remote add --mirror -f origin git://github.com/jvelilla/eTokyoCabinet.git
git remote add -f mirror git@github.com:Eiffel-World/eTokyoCabinet.git
git fetch origin
git fetch mirror
git push --mirror mirror
