#!/bin/sh

mkdir ../svnrepo/freeelks-svn
cd ../svnrepo/freeelks-svn
git svn init https://freeelks.svn.sourceforge.net/svnroot/freeelks -T trunk -b branches -t tags
git svn fetch
git checkout -b EiffelSoftware EiffelSoftware
git checkout master
git checkout -b Eiffel_66 Eiffel_66
git checkout master
git checkout -b model_based_contracts model_based_contracts
git checkout master
git checkout -b trunk trunk
git checkout master
git tag EiffelSoftware remotes/tags/EiffelSoftware
git tag Eiffel_60 remotes/tags/Eiffel_60
git tag Eiffel_61 remotes/tags/Eiffel_61
git tag start remotes/tags/start

git remote add -f mirror git@github.com:Eiffel-World/freeelks-svn.git
git gc
git svn rebase
git push -u --mirror mirror
