#!/bin/sh

mkdir ../gobo
cd ../gobo
git init
git config core.bare true
git remote add --mirror -f origin git://github.com/gobo-eiffel/gobo.git
git remote add -f mirror git@github.com:Eiffel-World/gobo.git
git fetch origin
git fetch mirror
git push --mirror mirror
