#!/bin/sh

mkdir ../ejson-svn
cd ../ejson-svn
git svn init https://svn.origo.ethz.ch/ejson -T trunk -b branches -t tags
git svn fetch
git checkout -b trunk_ise trunk_ise
git checkout master
git checkout -b trunk trunk
git checkout master
git checkout -b POC-converters-factory POC-converters-factory
git checkout master
git checkout -b RB-0.1 RB-0.1
git checkout master
git remote add -f mirror git@github.com:Eiffel-World/ejson-svn.git
git gc
git svn rebase
git push -u --mirror mirror
