#!/bin/sh

mkdir ../cvsrepo/safe-lib
cd ../cvsrepo/safe-lib
mkdir _git
cvs -d:pserver:anonymous:@safe.cvs.sourceforge.net:/cvsroot/safe login
cvs -z3 -d:pserver:anonymous:@safe.cvs.sourceforge.net:/cvsroot/safe co -P lib
cd lib
git cvsimport -p x -v -C  ../_git -a
cd ../_git
git status

git remote add -f mirror git@github.com:Eiffel-World/safe-lib.git
git gc
git push -u --mirror mirror
